name: Docker Image CI for GHCR

on:
  pull_request:
    branches:
      - main  # or the branch you want to trigger on
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: |
          docker login --username ${{ secrets.GH_USERNAME }} --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Build Docker image
        run: docker build . --tag ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_813 }}
          images: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest
