name: Docker Image and Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest
        file: ./Dockerfile

    - name: Test Docker image
      run: |
        docker run --rm ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest some-test-command

    - name: Scan Docker image
      uses: aquasecurity/trivy-action@v0.0.12
      with:
        image-ref: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_813 }}
        images: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest
