name: Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ secrets.GH_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build --no-cache -t ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_813 }}
          images: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:latest
