name: Docker Image PR Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:pr-${{ github.event.pull_request.number }}
        file: ./Dockerfile

    - name: Test Docker image
      run: |
        docker run --rm ghcr.io/jasmininnaka24/project-simulation-pipeline-container:pr-${{ github.event.pull_request.number }} some-test-command

    # Optionally: Scan Docker image for vulnerabilities
    - name: Scan Docker image
      uses: aquasecurity/trivy-action@v0.0.12
      with:
        image-ref: ghcr.io/jasmininnaka24/project-simulation-pipeline-container:pr-${{ github.event.pull_request.number }}

