name: Selenium Testing

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  test_and_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest pytest-html webdriver-manager

      - name: Create test results directory
        run: mkdir -p tests_results  # Create the directory to store test results

      - name: Run all tests
        run: |
          pytest --tb=short --html=tests_results/test_report.html --self-contained-html
          # Run all tests and generate an HTML report in the results directory

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: tests_results/test_report.html
          # Upload the test report as an artifact
