name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # Use the default GITHUB_TOKEN
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Ensure this secret is set in your repo
        with:
          args: |
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION_KEY }}
            # Uncomment and configure if necessary
            # -Dsonar.sources=
            # -Dsonar.tests=
            # -Dsonar.verbose=
          projectBaseDir: .
